In [25]:
#Setup
import numpy as np

x = np.array([1.2,-0.5,3.1,0.8])

w1 = np.array([
    [0.1, -0.2, 0.3, -0.4, 0.5],
    [0.6, -0.7, 0.8, -0.9, 1.0],
    [-0.1, 0.2, -0.3, 0.4, -0.5],
    [0.6, 0.7, -0.8, -0.9, 0.1]
])
b1 = np.array([0.1, -0.2, 0.4, -0.4, 0.5])

w2 = np.array([
    [0.2, -0.3, 0.4, 0.1, -0.2],
    [0.5, 0.6, -0.7, -0.8, 0.3],
    [-0.1, 0.2, 0.3, -0.4, 0.5],
    [0.5, -0.6, 0.7, 0.8, -0.1],
    [-0.2, 0.4, -0.4, 0.5, 0.6]
])
b2 = np.array([-0.1, 0.2, -0.3, 0.4, -0.5])

w3 = np.array([
    [1.0, -0.5, 0.3],
    [0.3, 0.8, -0.2],
    [-0.6, 1.2, 0.4],
    [0.4, -0.7, 0.9],
    [0.2, -0.1, 0.5]
])
b3= np.array([0.2, -0.3, 0.1])

In [19]:
#A.
#z1 = x.w1+b1
z1 = np.dot(x,w1)+b1
print(z1)


[ 0.09  1.09 -1.21  0.09 -0.87]


In [20]:
#B.
# a1 = ReLU(z1) = max(0, z1)
a1 = np.maximum(0, z1)
print(a1)

[0.09 1.09 0.   0.09 0.  ]


In [22]:
#C.
#z2 = a1.w2+b2
z2 = np.dot(a1,w2)+b2
print(z2)

[ 0.508  0.773 -0.964 -0.391 -0.2  ]


In [23]:
#D.
# a2 = ReLU(z2) = max(0,z2)
a2 = np.maximum(0,z2)
print(a2)

[0.508 0.773 0.    0.    0.   ]


In [26]:
#E.
# z3 = a2.w3+b3
z3 = np.dot(a2,w3)+b3
print(z3)

[0.9399 0.0644 0.0978]


In [27]:
#F
#Softmax(z3)
def softmax(z3):
    z3 = z3- max(z3)
    exp_z3 = np.exp(z3 - np.max(z3))
    return exp_z3 / np.sum(exp_z3)

print(softmax(z3))

[0.54128414 0.22552801 0.23318785]
