In [ ]:
import cv2
import numpy as np

# Membaca gambar
image = cv2.imread('gambar.jpg') # BGR format
gray_image = cv2.imread('gambar.jpg', cv2.IMREAD_GRAYSCALE)

In [11]:
print('--- Informasi Citra ---')
# Dimensi gambar
height, width = image.shape[:2] # Untuk warna
# height, width = gray_image.shape # Untuk grayscale

# Tipe data
print(f"Dimensi: {width}x{height}")
print(f"Tipe data: {image.dtype}")
print(f"Range nilai: {image.min()} - {image.max()}")
# Untuk gambar warna
channels = image.shape[2] # Jumlah channel
print(f"Jumlah channel: {channels}")

--- Informasi Citra ---
Dimensi: 252x359
Tipe data: uint8
Range nilai: 0 - 255
Jumlah channel: 3


In [16]:
print('Modifikasi Pixel (blurring)')
import numpy as np
from scipy.signal import convolve2d
f= np.array(image)
g= np.array([[(1/9) for _ in range(3)] for _ in range(3)])

def konvolusi(matriksinput, matriksfilter):
    dim_line_filter = len(matriksfilter)
    dim_col_filter = len(matriksfilter[0]) 
    dim_line_input = len(matriksinput)
    dim_col_input = len(matriksinput[0])

    dim_line_output = dim_line_input - dim_line_filter+1
    dim_col_output = dim_col_input - dim_col_filter+1

    output= [[0 for _ in range(dim_col_output)]
             for _ in range(dim_line_output)]
    
    for a in range(dim_line_output):
        for b in range(dim_col_output):
            nilai= 0
            for i in range(a,a+dim_line_filter):#Baris
                for j in range(b,b+dim_col_filter): #kolom
                    nilai += matriksinput[i][j]*matriksfilter[i-a][j-b]
            output[a][b]= nilai

    return np.array(output)

print(konvolusi(f,g))


Modifikasi Pixel (blurring)
[[[  0.33333333 219.33333333 253.33333333]
  [  1.         220.         254.        ]
  [  1.66666667 220.66666667 254.66666667]
  ...
  [166.33333333 249.66666667 253.66666667]
  [167.33333333 249.66666667 253.66666667]
  [182.33333333 250.55555556 253.88888889]]

 [[  0.33333333 219.33333333 253.33333333]
  [  1.         220.         254.        ]
  [  1.66666667 220.66666667 254.66666667]
  ...
  [167.44444444 250.88888889 254.66666667]
  [168.66666667 251.         254.66666667]
  [183.44444444 251.66666667 254.77777778]]

 [[  0.88888889 219.88888889 253.88888889]
  [  1.33333333 220.33333333 254.33333333]
  [  1.77777778 220.77777778 254.77777778]
  ...
  [167.77777778 251.22222222 255.        ]
  [169.         251.33333333 255.        ]
  [183.66666667 251.88888889 255.        ]]

 ...

 [[ 21.77777778 111.66666667 251.77777778]
  [ 19.66666667 111.22222222 252.        ]
  [ 18.11111111 111.11111111 252.66666667]
  ...
  [  1.33333333 155.33333333 254.

In [18]:
print('--- Modifikasi Pixel ---')
image[0,0]= [255,0,0]
image[100,150] = [0,0,255]
cv2.imwrite("modifikasi.jpg", image)

--- Modifikasi Pixel ---


True

In [21]:
#Konverse gray scale
gray_image = cv2.imread('gambar.jpg', cv2.IMREAD_GRAYSCALE)
cv2.imwrite("gray.png", gray_image)

True