In [ ]:
import numpy as np
from scipy.signal import convolve

f = np.array([
    [14,67,61,61,71,66],
    [61,66,18,55,21,90],
    [90,64,61,76,88,98],
    [34,99,31,23,40,91],
    [33,90,89,43,50,19],
    [98,76,54,65,91,12]
])

g = np.array([
    [0,-1,0],
    [-1,5,-1],
    [0,-1,0]
])

print(convolve(f, g, mode="valid"))

[[ 120 -153   99 -199]
 [   4  116  153  205]
 [ 276 -117  -75  -52]
 [ 153  227  -12   57]]


In [ ]:
#Fleksibel
f = [
    [14,67,61,61,71,66],
    [61,66,18,55,21,90],
    [90,64,61,76,88,98],
    [34,99,31,23,40,91],
    [33,90,89,43,50,19],
    [98,76,54,65,91,12]
]

g = [
    [0,-1,0],
    [-1,5,-1],
    [0,-1,0]
]

def konvolusi(matriksinput, matriksfilter):
    dim_line_filter = len(matriksfilter)
    dim_col_filter = len(matriksfilter[0]) 
    dim_line_input = len(matriksinput)
    dim_col_input = len(matriksinput[0])

    dim_line_output = dim_line_input - dim_line_filter+1
    dim_col_output = dim_col_input - dim_col_filter+1

    output= [[0 for _ in range(dim_col_output)]
             for _ in range(dim_line_output)]
    
    for a in range(dim_line_output):
        for b in range(dim_col_output):
            nilai= 0
            for i in range(a,a+dim_line_filter):#Baris
                for j in range(b,b+dim_col_filter): #kolom
                    nilai += matriksinput[i][j]*matriksfilter[i-a][j-b]
            output[a][b]= nilai

    return np.array(output)

print(konvolusi(f,g))

[[ 120 -153   99 -199]
 [   4  116  153  205]
 [ 276 -117  -75  -52]
 [ 153  227  -12   57]]
