In [ ]:
#1. Matriks Konvulsi
f = [
    [14,67,61,61,71,66],
    [61,66,18,55,21,90],
    [90,64,61,76,88,98],
    [34,99,31,23,40,91],
    [33,90,89,43,50,19],
    [98,76,54,65,91,12]
]

g = [
    [0,-1,0],
    [-1,5,-1],
    [0,-1,0]
]

def konvolusi(matriksinput, matriksfilter):
    dim_line_filter = len(matriksfilter)
    dim_col_filter = len(matriksfilter[0]) 
    dim_line_input = len(matriksinput)
    dim_col_input = len(matriksinput[0])

    dim_line_output = dim_line_input - dim_line_filter+1
    dim_col_output = dim_col_input - dim_col_filter+1

    output= [[0 for _ in range(dim_col_output)]
             for _ in range(dim_line_output)]
    
    for a in range(dim_line_output):
        for b in range(dim_col_output):
            nilai= 0
            for i in range(a,a+dim_line_filter):#Baris
                for j in range(b,b+dim_col_filter): #kolom
                    nilai += matriksinput[i][j]*matriksfilter[i-a][j-b]
            output[a][b]= nilai

    return output

hasil = konvolusi(f,g)
for i in range(len(hasil)):
    print(hasil[i])

[120, -153, 99, -199]
[4, 116, 153, 205]
[276, -117, -75, -52]
[153, 227, -12, 57]


In [ ]:
#Versi sederhana
import numpy as np
from scipy.signal import convolve2d

f = np.array([
    [14,67,61,61,71,66],
    [61,66,18,55,21,90],
    [90,64,61,76,88,98],
    [34,99,31,23,40,91],
    [33,90,89,43,50,19],
    [98,76,54,65,91,12]
])

g = np.array([
    [0,-1,0],
    [-1,5,-1],
    [0,-1,0]
])

hasil = convolve2d(f, g, mode="valid")
print(hasil)


[[ 120 -153   99 -199]
 [   4  116  153  205]
 [ 276 -117  -75  -52]
 [ 153  227  -12   57]]


In [1]:
#2
import cv2
import numpy as np

# Membaca gambar
image = cv2.imread('gambar.jpg') # BGR format
gray_image = cv2.imread('gambar.jpg', cv2.IMREAD_GRAYSCALE)

print('--- Informasi Citra ---')
image

--- Informasi Citra ---


array([[[  0, 219, 253],
        [  0, 219, 253],
        [  1, 220, 254],
        ...,
        [165, 247, 252],
        [165, 247, 252],
        [210, 251, 253]],

       [[  0, 219, 253],
        [  0, 219, 253],
        [  1, 220, 254],
        ...,
        [168, 250, 254],
        [168, 250, 254],
        [212, 253, 255]],

       [[  0, 219, 253],
        [  0, 219, 253],
        [  1, 220, 254],
        ...,
        [170, 252, 255],
        [170, 252, 255],
        [213, 253, 255]],

       ...,

       [[ 27, 114, 252],
        [ 24, 113, 252],
        [ 22, 111, 252],
        ...,
        [  0, 154, 255],
        [  0, 154, 255],
        [128, 204, 255]],

       [[ 29, 116, 254],
        [ 26, 115, 253],
        [ 22, 112, 252],
        ...,
        [  0, 153, 254],
        [  0, 153, 254],
        [128, 204, 255]],

       [[ 31, 119, 255],
        [ 28, 117, 255],
        [ 23, 113, 252],
        ...,
        [  0, 152, 253],
        [  0, 152, 253],
        [128, 204, 255]]